process.env.APP_URL ??= 'http://localhost:3000'
process.env.NEXT_PUBLIC_SITE_URL ??= 'http://localhost:3000'
process.env.NEXT_PUBLIC_SUPABASE_URL ??= 'http://127.0.0.1:54321'
process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ??= 'test-anon-key'
process.env.SUPABASE_SERVICE_ROLE_KEY ??= 'test-service-role-key'
process.env.OTP_HASH_SECRET ??= 'test-otp-secret'
process.env.FILE_TICKET_SECRET ??= 'test-file-ticket-secret'
process.env.OPENAI_API_KEY ??= 'test-openai-key'
