-- Baseline for production tables that existed before tracked migrations.
--
-- This migration intentionally only creates the pre-existing base tables. Later
-- migrations in this directory continue to add review, consent, gender,
-- planner source-linking, and routing columns/constraints in their original
-- order.
--
-- Reconciliation note: this baseline keeps student_case_requests as a base
-- table because the production-recorded 20260415 lifecycle migration references
-- it. The re-versioned 20260414010000 migration adds the historical indexes and
-- policies before 20260415 runs.

CREATE TABLE IF NOT EXISTS patient_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  age integer,
  phone text NOT NULL,
  country text,
  country_code text,
  preferred_language text,
  preferred_university text,
  treatment_type text NOT NULL,
  complaint_text text NOT NULL,
  urgency text NOT NULL,
  preferred_days text,
  pain_score integer,
  symptom_duration text,
  contact_method text,
  best_contact_time text,
  medical_condition text,
  prior_treatment boolean,
  consent boolean DEFAULT false,
  attachment_path text,
  attachment_name text,
  assigned_department text,
  target_student_level text,
  clinical_notes text,
  status text DEFAULT 'submitted',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS student_case_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL REFERENCES patient_requests(id) ON DELETE CASCADE,
  student_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  student_email text NOT NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  clinical_notes text,
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (case_id, student_id)
);

CREATE TABLE IF NOT EXISTS student_profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL UNIQUE,
  full_name text,
  phone text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS student_planner_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  event_date timestamptz NOT NULL,
  patient_id text,
  language text,
  created_at timestamptz DEFAULT now()
);
